#!/usr/bin/env python3
"""Helper to write the Playwright test script."""
import pathlib

out = pathlib.Path(__file__).parent.parent / "test_app.py"
L = []  # lines

def w(s=""):
    L.append(s)

w("import asyncio, subprocess, sys, time, urllib.request, os")
w("from pathlib import Path")
w()
w("async def main():")
w("    from playwright.async_api import async_playwright")
w("    errors = []")
w("    warnings = []")
w("    src_dir = Path(__file__).parent / 'src'")
w("    env = dict(os.environ)")
w("    env['PYTHONPATH'] = str(src_dir)")
w("    cmd_str = \"import sys; sys.path.insert(0, r'{}'); from src.app import app; app.run(debug=True, host='127.0.0.1', port=8050)\"")
w("    proc = subprocess.Popen(")
w("        [sys.executable, '-c', cmd_str.format(src_dir)],")
w("        env=env, stdout=subprocess.PIPE, stderr=subprocess.PIPE)")
w("    ready = False")
w("    for _ in range(60):")
w("        try:")
w("            urllib.request.urlopen('http://127.0.0.1:8050/_dash-layout', timeout=1)")
w("            ready = True; break")
w("        except Exception:")
w("            await asyncio.sleep(0.5)")
w("    if not ready:")
w("        proc.terminate()")
w("        print('ERROR: Dash server did not start in time.')")
w("        return errors, warnings")
w("    async with async_playwright() as p:")
w("        browser = await p.chromium.launch(headless=True)")
w("        page = await browser.new_page(viewport={'width': 1400, 'height': 900})")
w("        print('Browser started. Navigating to http://127.0.0.1:8050 ...')")
w("        try:")
w("            errors, warnings = await run_tests(page, errors, warnings)")
w("        except Exception as e:")
w("            import traceback; traceback.print_exc()")
w("            errors.append('FATAL test runner exception: {}'.format(e))")
w("        finally:")
w("            await browser.close()")
w("    proc.terminate()")
w("    return errors, warnings")
w()
w("")
w("async def run_tests(page, errors, warnings):")
w("    url = 'http://127.0.0.1:8050'")
w("    print('\\n=== TEST 1: Initial page load and tab structure ===')")
w("    await page.goto(url)")
w("    await page.wait_for_selector('#main-tabs', timeout=5000)")
w("    h1 = await page.locator('h1').first.inner_text()")
w("    print('  Page H1:', repr(h1))")
w("    if 'Survey Manager' not in h1:")
w("        errors.append(\"H1 text unexpected: {} (expected 'Survey Manager')\".format(repr(h1)))")
w("    tabs = await page.locator('.dcc-tabs .dcc-tab').all()")
w("    print('  Found {} tabs'.format(len(tabs)))")
w("    if len(tabs) != 3:")
w("        errors.append('Expected 3 tabs, found {}'.format(len(tabs)))")
w("    tab_labels = [await t.inner_text() for t in tabs]")
w("    print('  Tab labels:', tab_labels)")

w("    # === TEST 2: Survey Maker tab ===")
w("    print('\\n=== TEST 2: Survey Maker tab ===')")
w("    await page.click('text=Survey Maker')")
w("    await page.wait_for_selector('#maker-title', timeout=5000)")
w("    title_input = page.locator('#maker-title')")
w("    await title_input.fill('')")
w("    await title_input.type('Test Survey', delay=20)")
w("    print('  Title value:', repr(await title_input.input_value()))")
w("    desc_ta = page.locator('#maker-description')")
w("    await desc_ta.fill('')")
w("    await desc_ta.type('This is a test survey.', delay=20)")
w("    print('  Description value:', repr(await desc_ta.input_value()))")
w("    add_q_btn = page.locator('#maker-add-question')")
w("    for i in range(3):")
w("        await add_q_btn.click()")
w("        await page.wait_for_timeout(500)")
w("    print('  Clicked Add Question 3 times.')")
w("    q_text_inputs = page.locator('input[id*=\\\"_q_text_\\\"]')")
w("    n_q_text = await q_text_inputs.count()")
w("    print('  Question text inputs found:', n_q_text)")
w("    if await q_text_inputs.first.count() > 0:")
w("        await q_text_inputs.first.fill('')")
w("        await q_text_inputs.first.type('How satisfied are you?', delay=20)")

# Save Survey button test
w("")
w("    print('\\n  Clicking Save Survey...')")
w("    save_btn = page.locator('#maker-save-survey')")
w("    await save_btn.click()")
w("    await page.wait_for_timeout(1000)")
w("    status = await page.locator('#maker-status').inner_text()")
w("    print('  Status message after save:', repr(status))")

# TEST 3: Survey Taker tab
w("")
w("    # === TEST 3: Survey Taker tab ===")
w("    print('\\n=== TEST 3: Survey Taker tab ===')")
w("    await page.click('text=Survey Taker')")
w("    await page.wait_for_selector('#taker-survey-select', timeout=5000)")
w("    taker_dd = page.locator('#taker-survey-select .css-1gspdo7')")
w("    dd_text = await taker_dd.inner_text()")
w("    print('  Taker dropdown content:', repr(dd_text.strip()))")
w("    if 'Test Survey' in dd_text:")
w("        await page.click('#taker-survey-select', position={'x': 50, 'y': 10})")
w("        await page.wait_for_timeout(500)")
w("        n_dd_opts = await page.locator('#taker-survey-select .css-14lo706 li').count()")
w("        print('  Dropdown options visible:', n_dd_opts)")

# Inside the if block (n_dd_opts > 0)
w("        if n_dd_opts > 0:")
w("            await page.click('#taker-survey-select .css-14lo706 li')")
w("            await page.wait_for_timeout(800)")
w("            form_div = page.locator('#taker-survey-form')")
w("            form_html_len = len(await form_div.inner_html())")
w("            print('  Taker survey form HTML length:', form_html_len)")
w("            radios = await page.locator('.dcc-radio-item').count()")
w("            checks = await page.locator('.dcc-checklist-item').count()")
w("            textareas_count = await page.locator('textarea').count()")
w("            print('    Radio items:', radios, 'Checklist items:', checks, 'Textareas:', textareas_count)")
w("            taker_submit_btn = page.locator('#taker-submit')")
w("            n_taker_submits = await taker_submit_btn.count()")
w("            print('  Submit survey button visible:', bool(n_taker_submits))")
w("            form_inputs = page.locator(\"#taker-survey-form input[type=text], #taker-survey-form textarea\")")
w("            n_form_inputs = await form_inputs.count()")
w("            print('  Form text inputs/textareas count:', n_form_inputs)")

# Filling in form inputs (inside the n_dd_opts > 0 block)
w("            for fi in range(n_form_inputs):")
w("                inp = form_inputs.nth(fi)")
w("                tag = await inp.evaluate('el => el.tagName')")
w("                try:")
w("                    await inp.fill('')")
w("                    await inp.type('Answer to question {}'.format(fi+1), delay=20)")
w("                    print('    Filled input #{} (tag={}) with text.'.format(fi, tag))")
w("                except Exception as e:")
w("                    errors.append('Taker form input #{} fill/type error: {}'.format(fi, e))")
w("            print('\\n  Clicking Submit Survey...')")
w("            await taker_submit_btn.click()")
w("            await page.wait_for_timeout(1000)")
w("            thankyou = await page.locator('#taker-thankyou').inner_html()")
w("            print('  Thank-you div HTML:', repr(thankyou.strip()))")

# else branch for dd_text check
w("    else:")
w("        warnings.append(\"Test Survey not found in Taker dropdown. Content was: {}\".format(repr(dd_text.strip())))")

# TEST 4: Tab switch refreshes dropdown lists
w("")
w("    # === TEST 4: Tab switch refreshes dropdown lists ===")
w("    print('\\n=== TEST 4: Tab switch refreshes dropdowns ===')")
w("    await page.click('text=Survey Maker')")
w("    await page.wait_for_timeout(800)")
w("    maker_dd = page.locator('#maker-survey-select .css-1gspdo7')")
w("    maker_dd_text = await maker_dd.inner_text()")
w("    print('  Maker dropdown after switch:', repr(maker_dd_text.strip()))")

# TEST 5: Survey Analyzer tab
w("")
w("    # === TEST 5: Survey Analyzer tab ===")
w("    print('\\n=== TEST 5: Survey Analyzer tab ===')")
w("    await page.click('text=Survey Analyzer')")
w("    await page.wait_for_selector('#analyzer-survey-select', timeout=5000)")
w("    analyzer_dd = page.locator('#analyzer-survey-select .css-1gspdo7')")
w("    analyzer_dd_text = await analyzer_dd.inner_text()")
w("    print('  Analyzer dropdown content:', repr(analyzer_dd_text.strip()))")

w("    if 'Test Survey' in analyzer_dd_text:")
w("        await page.click('#analyzer-survey-select', position={'x': 50, 'y': 10})")
w("        await page.wait_for_timeout(500)")
w("        n_an_opts = await page.locator('#analyzer-survey-select .css-14lo706 li').count()")
w("        print('  Analyzer dropdown options visible:', n_an_opts)")
w("        if n_an_opts > 0:")
w("            await page.click('#analyzer-survey-select .css-14lo706 li')")
w("            await page.wait_for_timeout(800)")
w("            resp_count = await page.locator('#analyzer-response-count').inner_text()")
w("            print('  Response count header:', repr(resp_count))")
w("            dt_cells = page.locator('#analyzer-data-table .dash-spreadsheet-container, #analyzer-data-table .dash-cell')")
w("            n_dt_cells = await dt_cells.count()")
w("            print('  Data table cells found:', n_dt_cells)")

# return and main block
w("")
w("    return errors, warnings")
w("")
w("")
w("if __name__ == '__main__':")
w("    import traceback as tb")
w("    errors, warnings = asyncio.run(main())")
w("    print('\\n' + '=' * 70)")
w("    print('TEST SUMMARY')")
w("    print('=' * 70)")
w("    if not errors and not warnings:")
w("        print('All tests passed with no errors or warnings.')")
w("    else:")
w("        if warnings:")
w("            for w_warn in warnings:")
w("                print('WARNING: {}'.format(w_warn))")
w("        if errors:")
w("            print('\\nERRORS ({}):'.format(len(errors)))")
w("            for i, e in enumerate(errors, 1):")
w("                print('  {}. {}'.format(i, e))")

out.write_text("\n".join(L) + "\n")
print("All parts written to", out)
